# Generated by Django 5.1.1 on 2025-01-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('phone_num', models.IntegerField()),
                ('avatar', models.ImageField(default='images/avatar.png', upload_to='images/')),
            ],
        ),
    ]
