# Generated by Django 5.1.1 on 2025-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('discriptions', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=20)),
                ('photo', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('all', 'Усі страви'), ('first-dish', 'Перші страви'), ('salad', 'Салати'), ('dessert', 'Десерти'), ('drinks', 'Напої')], default='all', max_length=20)),
                ('price', models.IntegerField(verbose_name='price')),
            ],
        ),
    ]
